Работа с API
Изучить документацию API OF ICE AND FIRE
Получить информацию обо всех книгах и сохранить в pd.DataFrame - 1 балл

hint: используйте метод requests.get()

Получить информацию обо всех домах Вестероса (Houses) и сохранить в pd.DataFrame - 1 балл

hint: используйте метод requests.get()

Получить информацию обо всех домах Вестероса, у которых есть девиз, и сохранить в pd.DataFrame - 2 балла

hint: используйте метод requests.get(), используйте в ссылке запроса параметр hasTitles для фильтрации

In [1]:
import requests
import pandas as pd

In [45]:
api_base_url = 'https://anapioficeandfire.com/api'

In [52]:
all_books_list = []

for every page in (1, n):

  requests.get(f'{api_base_url}/books').json()
  all_books_list.append(page)
  count +=1

print(all_books)

[{'url': 'https://anapioficeandfire.com/api/books/1', 'name': 'A Game of Thrones', 'isbn': '978-0553103540', 'authors': ['George R. R. Martin'], 'numberOfPages': 694, 'publisher': 'Bantam Books', 'country': 'United States', 'mediaType': 'Hardcover', 'released': '1996-08-01T00:00:00', 'characters': ['https://anapioficeandfire.com/api/characters/2', 'https://anapioficeandfire.com/api/characters/12', 'https://anapioficeandfire.com/api/characters/13', 'https://anapioficeandfire.com/api/characters/16', 'https://anapioficeandfire.com/api/characters/20', 'https://anapioficeandfire.com/api/characters/27', 'https://anapioficeandfire.com/api/characters/31', 'https://anapioficeandfire.com/api/characters/38', 'https://anapioficeandfire.com/api/characters/39', 'https://anapioficeandfire.com/api/characters/40', 'https://anapioficeandfire.com/api/characters/41', 'https://anapioficeandfire.com/api/characters/42', 'https://anapioficeandfire.com/api/characters/46', 'https://anapioficeandfire.com/api/characters/54', 'https://anapioficeandfire.com/api/characters/56', 'https://anapioficeandfire.com/api/characters/57', 'https://anapioficeandfire.com/api/characters/60', 'https://anapioficeandfire.com/api/characters/61', 'https://anapioficeandfire.com/api/characters/62', 'https://anapioficeandfire.com/api/characters/66', 'https://anapioficeandfire.com/api/characters/67', 'https://anapioficeandfire.com/api/characters/69', 'https://anapioficeandfire.com/api/characters/79', 'https://anapioficeandfire.com/api/characters/89', 'https://anapioficeandfire.com/api/characters/107', 'https://anapioficeandfire.com/api/characters/115', 'https://anapioficeandfire.com/api/characters/116', 'https://anapioficeandfire.com/api/characters/120', 'https://anapioficeandfire.com/api/characters/125', 'https://anapioficeandfire.com/api/characters/128', 'https://anapioficeandfire.com/api/characters/129', 'https://anapioficeandfire.com/api/characters/130', 'https://anapioficeandfire.com/api/characters/135', 'https://anapioficeandfire.com/api/characters/137', 'https://anapioficeandfire.com/api/characters/142', 'https://anapioficeandfire.com/api/characters/147', 'https://anapioficeandfire.com/api/characters/149', 'https://anapioficeandfire.com/api/characters/150', 'https://anapioficeandfire.com/api/characters/151', 'https://anapioficeandfire.com/api/characters/160', 'https://anapioficeandfire.com/api/characters/164', 'https://anapioficeandfire.com/api/characters/168', 'https://anapioficeandfire.com/api/characters/171', 'https://anapioficeandfire.com/api/characters/181', 'https://anapioficeandfire.com/api/characters/190', 'https://anapioficeandfire.com/api/characters/194', 'https://anapioficeandfire.com/api/characters/198', 'https://anapioficeandfire.com/api/characters/202', 'https://anapioficeandfire.com/api/characters/203', 'https://anapioficeandfire.com/api/characters/206', 'https://anapioficeandfire.com/api/characters/209', 'https://anapioficeandfire.com/api/characters/211', 'https://anapioficeandfire.com/api/characters/213', 'https://anapioficeandfire.com/api/characters/217', 'https://anapioficeandfire.com/api/characters/220', 'https://anapioficeandfire.com/api/characters/223', 'https://anapioficeandfire.com/api/characters/225', 'https://anapioficeandfire.com/api/characters/235', 'https://anapioficeandfire.com/api/characters/238', 'https://anapioficeandfire.com/api/characters/245', 'https://anapioficeandfire.com/api/characters/259', 'https://anapioficeandfire.com/api/characters/264', 'https://anapioficeandfire.com/api/characters/273', 'https://anapioficeandfire.com/api/characters/274', 'https://anapioficeandfire.com/api/characters/291', 'https://anapioficeandfire.com/api/characters/292', 'https://anapioficeandfire.com/api/characters/293', 'https://anapioficeandfire.com/api/characters/294', 'https://anapioficeandfire.com/api/characters/303', 'https://anapioficeandfire.com/api/characters/306', 'https://anapioficeandfire.com/api/characters/313', 'https://anapioficeandfire.com/api/characters/315', 'https://anapioficeandfire.com/api/characters/325', 'https://anapioficeandfire.com/api/characters/326', 'https://anapioficeandfire.com/api/characters/327', 'https://anapioficeandfire.com/api/characters/338', 'https://anapioficeandfire.com/api/characters/346', 'https://anapioficeandfire.com/api/characters/347', 'https://anapioficeandfire.com/api/characters/348', 'https://anapioficeandfire.com/api/characters/361', 'https://anapioficeandfire.com/api/characters/368', 'https://anapioficeandfire.com/api/characters/377', 'https://anapioficeandfire.com/api/characters/379', 'https://anapioficeandfire.com/api/characters/380', 'https://anapioficeandfire.com/api/characters/384', 'https://anapioficeandfire.com/api/characters/385', 'https://anapioficeandfire.com/api/characters/393', 'https://anapioficeandfire.com/api/characters/394', 'https://anapioficeandfire.com/api/characters/397', 'https://anapioficeandfire.com/api/characters/400', 'https://anapioficeandfire.com/api/characters/401', 'https://anapioficeandfire.com/api/characters/405', 'https://anapioficeandfire.com/api/characters/408', 'https://anapioficeandfire.com/api/characters/413', 'https://anapioficeandfire.com/api/characters/415', 'https://anapioficeandfire.com/api/characters/418', 'https://anapioficeandfire.com/api/characters/421', 'https://anapioficeandfire.com/api/characters/427', 'https://anapioficeandfire.com/api/characters/435', 'https://anapioficeandfire.com/api/characters/439', 'https://anapioficeandfire.com/api/characters/458', 'https://anapioficeandfire.com/api/characters/461', 'https://anapioficeandfire.com/api/characters/463', 'https://anapioficeandfire.com/api/characters/466', 'https://anapioficeandfire.com/api/characters/467', 'https://anapioficeandfire.com/api/characters/475', 'https://anapioficeandfire.com/api/characters/476', 'https://anapioficeandfire.com/api/characters/484', 'https://anapioficeandfire.com/api/characters/487', 'https://anapioficeandfire.com/api/characters/490', 'https://anapioficeandfire.com/api/characters/494', 'https://anapioficeandfire.com/api/characters/496', 'https://anapioficeandfire.com/api/characters/498', 'https://anapioficeandfire.com/api/characters/501', 'https://anapioficeandfire.com/api/characters/503', 'https://anapioficeandfire.com/api/characters/506', 'https://anapioficeandfire.com/api/characters/508', 'https://anapioficeandfire.com/api/characters/519', 'https://anapioficeandfire.com/api/characters/521', 'https://anapioficeandfire.com/api/characters/526', 'https://anapioficeandfire.com/api/characters/527', 'https://anapioficeandfire.com/api/characters/529', 'https://anapioficeandfire.com/api/characters/531', 'https://anapioficeandfire.com/api/characters/532', 'https://anapioficeandfire.com/api/characters/533', 'https://anapioficeandfire.com/api/characters/535', 'https://anapioficeandfire.com/api/characters/536', 'https://anapioficeandfire.com/api/characters/539', 'https://anapioficeandfire.com/api/characters/547', 'https://anapioficeandfire.com/api/characters/557', 'https://anapioficeandfire.com/api/characters/558', 'https://anapioficeandfire.com/api/characters/562', 'https://anapioficeandfire.com/api/characters/565', 'https://anapioficeandfire.com/api/characters/572', 'https://anapioficeandfire.com/api/characters/584', 'https://anapioficeandfire.com/api/characters/585', 'https://anapioficeandfire.com/api/characters/586', 'https://anapioficeandfire.com/api/characters/588', 'https://anapioficeandfire.com/api/characters/595', 'https://anapioficeandfire.com/api/characters/600', 'https://anapioficeandfire.com/api/characters/604', 'https://anapioficeandfire.com/api/characters/605', 'https://anapioficeandfire.com/api/characters/613', 'https://anapioficeandfire.com/api/characters/615', 'https://anapioficeandfire.com/api/characters/622', 'https://anapioficeandfire.com/api/characters/631', 'https://anapioficeandfire.com/api/characters/632', 'https://anapioficeandfire.com/api/characters/635', 'https://anapioficeandfire.com/api/characters/640', 'https://anapioficeandfire.com/api/characters/649', 'https://anapioficeandfire.com/api/characters/650', 'https://anapioficeandfire.com/api/characters/651', 'https://anapioficeandfire.com/api/characters/672', 'https://anapioficeandfire.com/api/characters/677', 'https://anapioficeandfire.com/api/characters/688', 'https://anapioficeandfire.com/api/characters/691', 'https://anapioficeandfire.com/api/characters/692', 'https://anapioficeandfire.com/api/characters/694', 'https://anapioficeandfire.com/api/characters/695', 'https://anapioficeandfire.com/api/characters/701', 'https://anapioficeandfire.com/api/characters/709', 'https://anapioficeandfire.com/api/characters/714', 'https://anapioficeandfire.com/api/characters/718', 'https://anapioficeandfire.com/api/characters/721', 'https://anapioficeandfire.com/api/characters/724', 'https://anapioficeandfire.com/api/characters/725', 'https://anapioficeandfire.com/api/characters/731', 'https://anapioficeandfire.com/api/characters/734', 'https://anapioficeandfire.com/api/characters/749', 'https://anapioficeandfire.com/api/characters/751', 'https://anapioficeandfire.com/api/characters/752', 'https://anapioficeandfire.com/api/characters/754', 'https://anapioficeandfire.com/api/characters/755', 'https://anapioficeandfire.com/api/characters/759', 'https://anapioficeandfire.com/api/characters/766', 'https://anapioficeandfire.com/api/characters/768', 'https://anapioficeandfire.com/api/characters/775', 'https://anapioficeandfire.com/api/characters/778', 'https://anapioficeandfire.com/api/characters/779', 'https://anapioficeandfire.com/api/characters/782', 'https://anapioficeandfire.com/api/characters/784', 'https://anapioficeandfire.com/api/characters/786', 'https://anapioficeandfire.com/api/characters/797', 'https://anapioficeandfire.com/api/characters/805', 'https://anapioficeandfire.com/api/characters/806', 'https://anapioficeandfire.com/api/characters/814', 'https://anapioficeandfire.com/api/characters/815', 'https://anapioficeandfire.com/api/characters/820', 'https://anapioficeandfire.com/api/characters/823', 'https://anapioficeandfire.com/api/characters/827', 'https://anapioficeandfire.com/api/characters/828', 'https://anapioficeandfire.com/api/characters/829', 'https://anapioficeandfire.com/api/characters/832', 'https://anapioficeandfire.com/api/characters/837', 'https://anapioficeandfire.com/api/characters/844', 'https://anapioficeandfire.com/api/characters/850', 'https://anapioficeandfire.com/api/characters/852', 'https://anapioficeandfire.com/api/characters/860', 'https://anapioficeandfire.com/api/characters/862', 'https://anapioficeandfire.com/api/characters/867', 'https://anapioficeandfire.com/api/characters/869', 'https://anapioficeandfire.com/api/characters/876', 'https://anapioficeandfire.com/api/characters/884', 'https://anapioficeandfire.com/api/characters/886', 'https://anapioficeandfire.com/api/characters/887', 'https://anapioficeandfire.com/api/characters/891', 'https://anapioficeandfire.com/api/characters/892', 'https://anapioficeandfire.com/api/characters/894', 'https://anapioficeandfire.com/api/characters/901', 'https://anapioficeandfire.com/api/characters/903', 'https://anapioficeandfire.com/api/characters/909', 'https://anapioficeandfire.com/api/characters/912', 'https://anapioficeandfire.com/api/characters/913', 'https://anapioficeandfire.com/api/characters/916', 'https://anapioficeandfire.com/api/characters/933', 'https://anapioficeandfire.com/api/characters/945', 'https://anapioficeandfire.com/api/characters/954', 'https://anapioficeandfire.com/api/characters/955', 'https://anapioficeandfire.com/api/characters/969', 'https://anapioficeandfire.com/api/characters/972', 'https://anapioficeandfire.com/api/characters/975', 'https://anapioficeandfire.com/api/characters/983', 'https://anapioficeandfire.com/api/characters/984', 'https://anapioficeandfire.com/api/characters/994', 'https://anapioficeandfire.com/api/characters/1010', 'https://anapioficeandfire.com/api/characters/1017', 'https://anapioficeandfire.com/api/characters/1022', 'https://anapioficeandfire.com/api/characters/1023', 'https://anapioficeandfire.com/api/characters/1025', 'https://anapioficeandfire.com/api/characters/1029', 'https://anapioficeandfire.com/api/characters/1033', 'https://anapioficeandfire.com/api/characters/1034', 'https://anapioficeandfire.com/api/characters/1043', 'https://anapioficeandfire.com/api/characters/1044', 'https://anapioficeandfire.com/api/characters/1049', 'https://anapioficeandfire.com/api/characters/1051', 'https://anapioficeandfire.com/api/characters/1055', 'https://anapioficeandfire.com/api/characters/1063', 'https://anapioficeandfire.com/api/characters/1068', 'https://anapioficeandfire.com/api/characters/1069', 'https://anapioficeandfire.com/api/characters/1072', 'https://anapioficeandfire.com/api/characters/1074', 'https://anapioficeandfire.com/api/characters/1076', 'https://anapioficeandfire.com/api/characters/1077', 'https://anapioficeandfire.com/api/characters/1079', 'https://anapioficeandfire.com/api/characters/1080', 'https://anapioficeandfire.com/api/characters/1089', 'https://anapioficeandfire.com/api/characters/1090', 'https://anapioficeandfire.com/api/characters/1091', 'https://anapioficeandfire.com/api/characters/1093', 'https://anapioficeandfire.com/api/characters/1096', 'https://anapioficeandfire.com/api/characters/1104', 'https://anapioficeandfire.com/api/characters/1106', 'https://anapioficeandfire.com/api/characters/1107', 'https://anapioficeandfire.com/api/characters/1110', 'https://anapioficeandfire.com/api/characters/1113', 'https://anapioficeandfire.com/api/characters/1114', 'https://anapioficeandfire.com/api/characters/1116', 'https://anapioficeandfire.com/api/characters/1120', 'https://anapioficeandfire.com/api/characters/1122', 'https://anapioficeandfire.com/api/characters/1124', 'https://anapioficeandfire.com/api/characters/1131', 'https://anapioficeandfire.com/api/characters/1132', 'https://anapioficeandfire.com/api/characters/1140', 'https://anapioficeandfire.com/api/characters/1142', 'https://anapioficeandfire.com/api/characters/1147', 'https://anapioficeandfire.com/api/characters/1152', 'https://anapioficeandfire.com/api/characters/1158', 'https://anapioficeandfire.com/api/characters/1165', 'https://anapioficeandfire.com/api/characters/1166', 'https://anapioficeandfire.com/api/characters/1178', 'https://anapioficeandfire.com/api/characters/1188', 'https://anapioficeandfire.com/api/characters/1193', 'https://anapioficeandfire.com/api/characters/1214', 'https://anapioficeandfire.com/api/characters/1219', 'https://anapioficeandfire.com/api/characters/1228', 'https://anapioficeandfire.com/api/characters/1245', 'https://anapioficeandfire.com/api/characters/1247', 'https://anapioficeandfire.com/api/characters/1253', 'https://anapioficeandfire.com/api/characters/1260', 'https://anapioficeandfire.com/api/characters/1262', 'https://anapioficeandfire.com/api/characters/1265', 'https://anapioficeandfire.com/api/characters/1266', 'https://anapioficeandfire.com/api/characters/1267', 'https://anapioficeandfire.com/api/characters/1268', 'https://anapioficeandfire.com/api/characters/1269', 'https://anapioficeandfire.com/api/characters/1275', 'https://anapioficeandfire.com/api/characters/1277', 'https://anapioficeandfire.com/api/characters/1278', 'https://anapioficeandfire.com/api/characters/1280', 'https://anapioficeandfire.com/api/characters/1282', 'https://anapioficeandfire.com/api/characters/1284', 'https://anapioficeandfire.com/api/characters/1289', 'https://anapioficeandfire.com/api/characters/1296', 'https://anapioficeandfire.com/api/characters/1299', 'https://anapioficeandfire.com/api/characters/1304', 'https://anapioficeandfire.com/api/characters/1317', 'https://anapioficeandfire.com/api/characters/1326', 'https://anapioficeandfire.com/api/characters/1333', 'https://anapioficeandfire.com/api/characters/1335', 'https://anapioficeandfire.com/api/characters/1336', 'https://anapioficeandfire.com/api/characters/1340', 'https://anapioficeandfire.com/api/characters/1346', 'https://anapioficeandfire.com/api/characters/1352', 'https://anapioficeandfire.com/api/characters/1355', 'https://anapioficeandfire.com/api/characters/1373', 'https://anapioficeandfire.com/api/characters/1383', 'https://anapioficeandfire.com/api/characters/1389', 'https://anapioficeandfire.com/api/characters/1396', 'https://anapioficeandfire.com/api/characters/1409', 'https://anapioficeandfire.com/api/characters/1410', 'https://anapioficeandfire.com/api/characters/1418', 'https://anapioficeandfire.com/api/characters/1430', 'https://anapioficeandfire.com/api/characters/1434', 'https://anapioficeandfire.com/api/characters/1442', 'https://anapioficeandfire.com/api/characters/1444', 'https://anapioficeandfire.com/api/characters/1453', 'https://anapioficeandfire.com/api/characters/1455', 'https://anapioficeandfire.com/api/characters/1456', 'https://anapioficeandfire.com/api/characters/1463', 'https://anapioficeandfire.com/api/characters/1466', 'https://anapioficeandfire.com/api/characters/1468', 'https://anapioficeandfire.com/api/characters/1470', 'https://anapioficeandfire.com/api/characters/1488', 'https://anapioficeandfire.com/api/characters/1499', 'https://anapioficeandfire.com/api/characters/1502', 'https://anapioficeandfire.com/api/characters/1515', 'https://anapioficeandfire.com/api/characters/1520', 'https://anapioficeandfire.com/api/characters/1523', 'https://anapioficeandfire.com/api/characters/1526', 'https://anapioficeandfire.com/api/characters/1529', 'https://anapioficeandfire.com/api/characters/1530', 'https://anapioficeandfire.com/api/characters/1531', 'https://anapioficeandfire.com/api/characters/1540', 'https://anapioficeandfire.com/api/characters/1547', 'https://anapioficeandfire.com/api/characters/1548', 'https://anapioficeandfire.com/api/characters/1549', 'https://anapioficeandfire.com/api/characters/1551', 'https://anapioficeandfire.com/api/characters/1559', 'https://anapioficeandfire.com/api/characters/1560', 'https://anapioficeandfire.com/api/characters/1565', 'https://anapioficeandfire.com/api/characters/1566', 'https://anapioficeandfire.com/api/characters/1568', 'https://anapioficeandfire.com/api/characters/1570', 'https://anapioficeandfire.com/api/characters/1573', 'https://anapioficeandfire.com/api/characters/1585', 'https://anapioficeandfire.com/api/characters/1596', 'https://anapioficeandfire.com/api/characters/1602', 'https://anapioficeandfire.com/api/characters/1620', 'https://anapioficeandfire.com/api/characters/1624', 'https://anapioficeandfire.com/api/characters/1627', 'https://anapioficeandfire.com/api/characters/1631', 'https://anapioficeandfire.com/api/characters/1649', 'https://anapioficeandfire.com/api/characters/1650', 'https://anapioficeandfire.com/api/characters/1660', 'https://anapioficeandfire.com/api/characters/1662', 'https://anapioficeandfire.com/api/characters/1665', 'https://anapioficeandfire.com/api/characters/1666', 'https://anapioficeandfire.com/api/characters/1670', 'https://anapioficeandfire.com/api/characters/1674', 'https://anapioficeandfire.com/api/characters/1675', 'https://anapioficeandfire.com/api/characters/1677', 'https://anapioficeandfire.com/api/characters/1682', 'https://anapioficeandfire.com/api/characters/1697', 'https://anapioficeandfire.com/api/characters/1706', 'https://anapioficeandfire.com/api/characters/1708', 'https://anapioficeandfire.com/api/characters/1710', 'https://anapioficeandfire.com/api/characters/1713', 'https://anapioficeandfire.com/api/characters/1715', 'https://anapioficeandfire.com/api/characters/1717', 'https://anapioficeandfire.com/api/characters/1721', 'https://anapioficeandfire.com/api/characters/1724', 'https://anapioficeandfire.com/api/characters/1725', 'https://anapioficeandfire.com/api/characters/1727', 'https://anapioficeandfire.com/api/characters/1741', 'https://anapioficeandfire.com/api/characters/1742', 'https://anapioficean

In [11]:
pd_with_books = pd.DataFrame(all_books)

In [41]:
pd_with_books.head()

,url,name,isbn,authors,numberOfPages,publisher,country,mediaType,released,characters,povCharacters
0,https://anapioficeandfire.com/api/books/1,A Game of Thrones,978-0553103540,[George R. R. Martin],694,Bantam Books,United States,Hardcover,1996-08-01T00:00:00,[https://anapioficeandfire.com/api/characters/...,[https://anapioficeandfire.com/api/characters/...
1,https://anapioficeandfire.com/api/books/2,A Clash of Kings,978-0553108033,[George R. R. Martin],768,Bantam Books,United States,Hardback,1999-02-02T00:00:00,[https://anapioficeandfire.com/api/characters/...,[https://anapioficeandfire.com/api/characters/...
2,https://anapioficeandfire.com/api/books/3,A Storm of Swords,978-0553106633,[George R. R. Martin],992,Bantam Books,United States,Hardcover,2000-10-31T00:00:00,[https://anapioficeandfire.com/api/characters/...,[https://anapioficeandfire.com/api/characters/...
3,https://anapioficeandfire.com/api/books/4,The Hedge Knight,978-0976401100,[George R. R. Martin],164,Dabel Brothers Publishing,United States,GraphicNovel,2005-03-09T00:00:00,[https://anapioficeandfire.com/api/characters/...,[https://anapioficeandfire.com/api/characters/...
4,https://anapioficeandfire.com/api/books/5,A Feast for Crows,978-0553801507,[George R. R. Martin],784,Bantam Books,United Status,Hardcover,2005-11-08T00:00:00,[https://anapioficeandfire.com/api/characters/...,[https://anapioficeandfire.com/api/characters/...

In [42]:
pd_with_books.count()

url              10
name             10
isbn             10
authors          10
numberOfPages    10
publisher        10
country          10
mediaType        10
released         10
characters       10
povCharacters    10
dtype: int64

In [54]:
api_base_url = "https://www.anapioficeandfire.com/api"
all_books_list = []

count = 0
page = 1

while True:
    response = requests.get(f'{api_base_url}/books?page={page}')
    data = response.json()

    if not data:
        break

    all_books_list.extend(data)
    count += 1
    page += 1

In [55]:
pd_with_books = pd.DataFrame(all_books_list)

In [56]:
pd_with_books.head()

,url,name,isbn,authors,numberOfPages,publisher,country,mediaType,released,characters,povCharacters
0,https://www.anapioficeandfire.com/api/books/1,A Game of Thrones,978-0553103540,[George R. R. Martin],694,Bantam Books,United States,Hardcover,1996-08-01T00:00:00,[https://www.anapioficeandfire.com/api/charact...,[https://www.anapioficeandfire.com/api/charact...
1,https://www.anapioficeandfire.com/api/books/2,A Clash of Kings,978-0553108033,[George R. R. Martin],768,Bantam Books,United States,Hardback,1999-02-02T00:00:00,[https://www.anapioficeandfire.com/api/charact...,[https://www.anapioficeandfire.com/api/charact...
2,https://www.anapioficeandfire.com/api/books/3,A Storm of Swords,978-0553106633,[George R. R. Martin],992,Bantam Books,United States,Hardcover,2000-10-31T00:00:00,[https://www.anapioficeandfire.com/api/charact...,[https://www.anapioficeandfire.com/api/charact...
3,https://www.anapioficeandfire.com/api/books/4,The Hedge Knight,978-0976401100,[George R. R. Martin],164,Dabel Brothers Publishing,United States,GraphicNovel,2005-03-09T00:00:00,[https://www.anapioficeandfire.com/api/charact...,[https://www.anapioficeandfire.com/api/charact...
4,https://www.anapioficeandfire.com/api/books/5,A Feast for Crows,978-0553801507,[George R. R. Martin],784,Bantam Books,United Status,Hardcover,2005-11-08T00:00:00,[https://www.anapioficeandfire.com/api/charact...,[https://www.anapioficeandfire.com/api/charact...

In [57]:
pd_with_books.count()

url              12
name             12
isbn             12
authors          12
numberOfPages    12
publisher        12
country          12
mediaType        12
released         12
characters       12
povCharacters    12
dtype: int64

In [58]:
api_base_url = "https://www.anapioficeandfire.com/api"
all_houses_list = []

count = 0
page = 1

while True:
    response = requests.get(f'{api_base_url}/houses?page={page}')
    data = response.json()

    if not data:
        break

    all_houses_list.extend(data)
    count += 1
    page += 1

In [64]:
pd_with_houses = pd.DataFrame(all_houses_list)

In [65]:
pd_with_houses.head()

,url,name,region,coatOfArms,words,titles,seats,currentLord,heir,overlord,founded,founder,diedOut,ancestralWeapons,cadetBranches,swornMembers
0,https://www.anapioficeandfire.com/api/houses/1,House Algood,The Westerlands,"A golden wreath, on a blue field with a gold b...",,[],[],,,https://www.anapioficeandfire.com/api/houses/229,,,,[],[],[]
1,https://www.anapioficeandfire.com/api/houses/2,House Allyrion of Godsgrace,Dorne,"Gyronny Gules and Sable, a hand couped Or",No Foe May Pass,[],[Godsgrace],https://www.anapioficeandfire.com/api/characte...,https://www.anapioficeandfire.com/api/characte...,https://www.anapioficeandfire.com/api/houses/285,,,,[],[],[https://www.anapioficeandfire.com/api/charact...
2,https://www.anapioficeandfire.com/api/houses/3,House Amber,The North,,,[],[],,,,,,,[],[],[]
3,https://www.anapioficeandfire.com/api/houses/4,House Ambrose,The Reach,"Or, semy of ants gules",Never Resting,[],[],https://www.anapioficeandfire.com/api/characte...,,https://www.anapioficeandfire.com/api/houses/398,,,,[],[],[https://www.anapioficeandfire.com/api/charact...
4,https://www.anapioficeandfire.com/api/houses/5,House Appleton of Appleton,The Reach,"Or, an apple tree eradicated proper fructed gu...",,[],[Appleton],,,https://www.anapioficeandfire.com/api/houses/398,,,,[],[],[]

In [66]:
pd_with_houses.count()

url                 444
name                444
region              444
coatOfArms          444
words               444
titles              444
seats               444
currentLord         444
heir                444
overlord            444
founded             444
founder             444
diedOut             444
ancestralWeapons    444
cadetBranches       444
swornMembers        444
dtype: int64

In [71]:
pd_westeros = pd_with_houses[pd_with_houses['region'] == 'The Westerlands']

In [72]:
pd_westeros.head()

,url,name,region,coatOfArms,words,titles,seats,currentLord,heir,overlord,founded,founder,diedOut,ancestralWeapons,cadetBranches,swornMembers
0,https://www.anapioficeandfire.com/api/houses/1,House Algood,The Westerlands,"A golden wreath, on a blue field with a gold b...",,[],[],,,https://www.anapioficeandfire.com/api/houses/229,,,,[],[],[]
12,https://www.anapioficeandfire.com/api/houses/13,House Banefort of Banefort,The Westerlands,"A black hooded man, on a grey field, within a ...",,[Lord of Banefort],[Banefort],https://www.anapioficeandfire.com/api/characte...,,https://www.anapioficeandfire.com/api/houses/229,,https://www.anapioficeandfire.com/api/characte...,,[],[],[https://www.anapioficeandfire.com/api/charact...
19,https://www.anapioficeandfire.com/api/houses/20,House Bettley,The Westerlands,"Three blue beetles, on a gold field(Or, three ...",,[],[],,,https://www.anapioficeandfire.com/api/houses/229,,,,[],[],[https://www.anapioficeandfire.com/api/charact...
39,https://www.anapioficeandfire.com/api/houses/40,House Brax of Hornvale,The Westerlands,"A purple unicorn, on a silver field(Argent, a ...",,[],[Hornvale],https://www.anapioficeandfire.com/api/characte...,https://www.anapioficeandfire.com/api/characte...,https://www.anapioficeandfire.com/api/houses/229,,,,[],[],[https://www.anapioficeandfire.com/api/charact...
45,https://www.anapioficeandfire.com/api/houses/46,House Broom,The Westerlands,"A silver helm crested with a sprig of broom, o...",,[],[],,,https://www.anapioficeandfire.com/api/houses/229,,,,[],[],[https://www.anapioficeandfire.com/api/charact...

Не понял куда вписывать параметр

In [80]:
api_base_url = "https://www.anapioficeandfire.com/api"
all_houses_titles_list = []

count = 0
page = 1

while True:
    response = requests.get(f'{api_base_url}/houses?page={page}/hasTitles')
    data = response.json()

    if not data:
        break

    all_houses_titles_list.extend(data)
    count += 1
    page += 1

KeyboardInterrupt:

In [ ]:
Установить библиотеку psycopg2 (pip install psycopg2-binary)

Подключиться к БД - 1 балл

hint: используйте для подключения параметры Hostname, Database, User, Password, указанные на странице БД, и метод psycopg2.connect()

Получите 10 строк из таблицы rnc_database - 2 балла

hint: используйте методы conn.cursor(), cursor.execute(), cursor.fetchall(). В SQL-запросе не забудьте использовать LIMIT 10

Сохраните полученные данные в pd.DataFrame - 1 балл
Получите значения столбцов display_name, num_sequences, num_organisms, , url для 10 строк из таблицы rnc_database - 2 балла

hint: используйте методы conn.cursor(), cursor.execute(), cursor.fetchall(). В SQL-запросе не забудьте использовать LIMIT 10 и указать нужные вам столбцы

In [87]:
import psycopg2
conn = psycopg2.connect(
    host = 'hh-pgsql-public.ebi.ac.uk',
    port = '5432',
    database = 'pfmegrnargs',
    user = 'reader',
    password = 'NWDMCE5xdipIjRrp'
)

In [90]:
with conn.cursor() as cursor:
  cursor.execute('SELECT * FROM rnc_database limit 10' )
  rnc_database_10 = cursor.fetchall()

In [91]:
pd_rnc = pd.DataFrame(rnc_database_10)

In [92]:
pd_rnc.head()

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18
0,21,2017-05-02,RNACEN,NONCODE,146,NONCODE,Y,,NONCODE,,1130.0,201.0,244296.0,234669,7,is an integrated knowledge database dedicated ...,http://www.noncode.org/,"[{'upi': 'URS000019B796', 'taxid': 9606}, {'up...",[{'title': 'NONCODE 2016: an informative and v...
1,5,2017-05-17,RNACEN,VEGA,98,VEGA,N,,VEGA,PRJEB4568,NaN,NaN,NaN,0,0,is a repository for high-quality gene models p...,http://vega.sanger.ac.uk/,"[{'upi': 'URS00000B15DA', 'taxid': 9606}, {'up...",[{'title': 'The GENCODE v7 catalog of human lo...
2,26,2017-05-01,RNACEN,GENCODE,450,GENCODE,N,,GENCODE,,889.0,32.0,205012.0,47677,2,produces high quality reference gene annotatio...,http://gencodegenes.org/,"[{'upi': 'URS00000B15DA', 'taxid': 9606}, {'up...",[{'title': 'GENCODE: the reference human genom...
3,1,2017-05-01,RNACEN,ENA,968,ENA,Y,,ENA,,412.0,10.0,900074.0,12086180,814855,provides a comprehensive record of the world's...,https://www.ebi.ac.uk/ena/browser/,"[{'upi': 'URS00002D0E0C', 'taxid': 10090}, {'u...",[{'title': 'The European Nucleotide Archive in...
4,14,2017-05-01,RNACEN,TAIR,982,TAIR,Y,,TAIR,PRJ_TAIR,384.0,19.0,6227.0,4406,1,is a database of genetic and molecular biology...,http://www.arabidopsis.org/,"[{'upi': 'URS0000591E4F', 'taxid': 3702}, {'up...",[{'title': 'The Arabidopsis Information Resour...

In [94]:
with conn.cursor() as cursor:
  cursor.execute('SELECT display_name, num_sequences, num_organisms, url FROM rnc_database limit 10' )
  rnc_database_columns10 = cursor.fetchall()

In [95]:
pd_rnc_columns = pd.DataFrame(rnc_database_columns10)

In [96]:
pd_rnc_columns.head()

         0         1       2                                   3
0  NONCODE    234669       7             http://www.noncode.org/
1     VEGA         0       0           http://vega.sanger.ac.uk/
2  GENCODE     47677       2            http://gencodegenes.org/
3      ENA  12086180  814855  https://www.ebi.ac.uk/ena/browser/
4     TAIR      4406       1         http://www.arabidopsis.org/